### ISSUE TITLE
My brief experience with copilot - it tended to hallucinate!

### ISSUE THREAD

**Issue by will-henney** [dawg-at-irya/github-copilot-talk#1]
Hi Sundar. Many thanks for your talk yesterday.  So, I tried it out last night and had mixed results.  Some things worked fine, but it had real difficulties when I asked it: 

```python
# Find a line identification from AtomicLineList
```
and it suggested that I do 
```python
from astroquery.atomic import Atomic
line = Atomic.get_spectral_line_list(ion='H I', wavelength_min=6562.8, wavelength_max=6563.2)
```
which is wrong in a few respects: there is no `astroquery.atomic.Atomic` and there is no function `get_spectral_line_list()`.

I am not even sure where it was getting that from. I first thought it might be an old version of the API, but google gives zero hits for that function...

Have you seen any similar flights of fancy?

**Comment by sundarjhu** [comment]
Ha ha, yes I have! I've seen this sort of behaviour with ChatGPT myself.
The AI tries to "fill in" something for which it doesn't actually have
documentation. In my case, I asked for it to run the radiative transfer
code Hyperion (which is very poorly documented) for an AGB star with a
carbon-rich dust shell. While some of the import statements were grounded
in reality, the most important part (setting up the dust species) was
indeed accomplished by inventing a function set_carbon_dust that doesn't
exist. Each time I pointed out a function didn't exist, it apologised and
used a different guess for the same (set_mineralogy('carbon'), for example).
The AI still requires the programmer to review its code, especially in the
case of poorly-documented packages. One can also ensure better results by
having the prompts be as specific as possible. I tried a few variations of
your prompt, even going so far as to say "identify lines using
astroquery.AtomicLineList". It looks like it always fails at finding the
query_object method that is part of this package, and thus the invented
functions :D

**Comment by will-henney** [comment]
Looking on the positive side, you could argue that `get_spectral_line_list()` is a better name than `query_object()`  and so should be added to the API!  I guess that `query_object()`  is for uniformity across `astroquery`, although looking at the various subpackages, there is only partial consistency

**Comment by will-henney** [comment]
P.S. What do you think about turning on Discussions for the dawg-at-irya organization? Then this thread could be migrated to a Discussion, since it isn't really an Issue as such.

Also, we could encourage more people to join the organization. You could send invitations to the 4 people who are following
